cask_args appdir: "~/Applications"

tap "homebrew/bundle"
tap "homebrew/cask-fonts"

brew "asdf"
brew "cliclick"
brew "coreutils" # dependency: asdf
brew "curl" # dependency: asdf
brew "fzf"
brew "git" # dependency: asdf
brew "starship"
brew "wxwidgets" # dependency: asdf-erlang
brew "zsh-completions"

cask "affinity-publisher"
cask "alacritty"
cask "audacity"
cask "bitwarden"
cask "docker"
cask "firefox"
cask "font-jetbrains-mono-nerd-font"
cask "google-chrome"
cask "google-drive"
cask "kindle"
cask "maccy"
cask "microsoft-outlook"
cask "microsoft-teams"
cask "protonvpn"
cask "rectangle"
cask "signal"
cask "slack"
cask "spotify"
cask "visual-studio-code"
cask "zoom"
