[character]
success_symbol = "[➜](bold green)"
error_symbol = "[✗](bold red)"

[directory]
style = "blue"

[git_branch]
symbol = ""

[nodejs]
format = "via [⬢ $version](bold green) "

[time]
disabled = false
style = "green"