#!/bin/bash

chmod +x ./pkgs
chmod +x ./upgrade

/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

if [ -x "$(command -v brew)" ]; then
  ./pkgs install
fi
