'$schema' = 'https://starship.rs/config-schema.json'

command_timeout = 2000

format = '''
$all$fill $cmd_duration$time
$character
'''


[cmd_duration]
min_time = 0 # (always show)

[line_break]
disabled = true

[time]
disabled = false
