"$schema" = 'https://starship.rs/config-schema.json'

format = """
╔════════════════════════════════════════════════════════════════════════════════
$character$all
$character
"""

[character]
success_symbol = "[║](bold green)"
error_symbol = "[║](bold red)"

[line_break]
disabled=true

[nodejs]
format = "via [⬢ $version](bold green) "

[time]
disabled = false
style = "green"
