"$schema" = 'https://starship.rs/config-schema.json'

format = """
╔════════════════════════════════════════════════════════════════════════════════
║ $all
$character
"""

[character]
success_symbol = "[╚](bold green)"
error_symbol = "[╚](bold red)"

[cmd_duration]
min_time = 0

[line_break]
disabled = true

[time]
disabled = false
