'$schema' = 'https://starship.rs/config-schema.json'

command_timeout = 1000

format = '''
$all$fill $cmd_duration$time
$character
'''

[character]
success_symbol = '[\$](dimmed)'
error_symbol = '[\$](dimmed)'

[cmd_duration]
# show irrespective of duration
min_time = 0

[fill]
# symbol = "─"
# need this or else not displayed in Alacritty
style = 'dimmed'

[line_break]
disabled = true


[time]
disabled = false
