'$schema' = 'https://starship.rs/config-schema.json'

format = '''
$all$fill $cmd_duration$time
$character
'''

[cmd_duration]
min_time = 0 # (always show)

[line_break]
disabled = true

[time]
disabled = false
